access/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('', views.sign_in, name='login'),
	path('logout/', views.sign_out, name='logout'),
	# path('reset/password/', views.reset_password, name='forgot_password'),
	path('second-factor/', views.second_factor, name='second_factor'),

	path('password_reset/', views.reset_password, name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

dashboard/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
	path("", views.index, name="index"),
	path("dashboard-analytics/", views.dashboard_analytics, name="dashboard-analytics"),


]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

molymet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('',include('access.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

access/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager



class UserManager(BaseUserManager):
	use_in_migrations = True

	def _create_user(self, email, password, **extra_fields):
		if not email:
			raise ValueError('Users require an email field')
		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, email, password=None, **extra_fields):
		extra_fields.setdefault('is_staff', False)
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)
		extra_fields.setdefault('user_type', 1)

		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser must have is_staff=True.')
		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')

		return self._create_user(email, password, **extra_fields)


class User(AbstractUser):

	groups = models.ManyToManyField(
		Group,
		related_name='custom_user_set',  # Change this to a unique name
		blank=True,
		help_text=_(
			'The groups this user belongs to. A user will get all permissions '
			'granted to each of their groups.'
		),
		related_query_name='custom_user'
	)
	user_permissions = models.ManyToManyField(
		Permission,
		related_name='custom_user_permissions',  # Change this to a unique name
		blank=True,
		help_text='Specific permissions for this user.',
		related_query_name='custom_user'
	)

	USER_TYPE_CHOICES = (
		(1, 'Administrador'),
		# (2, 'Sólo lectura'),
	)

	username = None
	email = models.EmailField(_('Email'), unique=True)
	phone = models.CharField('Teléfono', max_length=20, null=True, blank=True)
	position = models.CharField('Cargo', max_length=100, null=True, blank=True)
	user_type = models.PositiveSmallIntegerField('Tipo de usuario', choices=USER_TYPE_CHOICES)
	active = models.BooleanField(default=True)

	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

dashboard/models.py
from django.db import models

# Create your models here.

access/forms.py
from django import forms
from django.forms import ModelForm
from .models import User

class LoginForm(forms.Form):
	username = forms.CharField(max_length=65)
	password = forms.CharField(max_length=65, widget=forms.PasswordInput)

class SecondFactorForm(forms.Form):
	second_factor = forms.CharField(max_length=10)

class ResetForm(forms.Form):
	email = forms.EmailField()

access/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.mail import send_mail
import random
from django.contrib.auth import views as auth_views

from .forms import LoginForm, ResetForm, SecondFactorForm

def send_2FA_email(request, user):
	# Generate a random 6-digit 2FA code
	code = str(random.randint(1000000, 9999999))
	print(code)
	# Store it in the session (You might prefer to store it in the database)
	request.session['2FA_code'] = code

	# Send email with the code
	send_mail(
		'Tu código 2FA',
		f'Tu código de verificación para 2FA es: {code}',
		'no-reply@help.clientis.tech',  # Your sending email
		[user.email],
		fail_silently=False,
	)
	print("Mail sent to", user.email)
	return

def verify_2FA_code(request, user, provided_code):
	stored_code = request.session.get('2FA_code', None)
	print(stored_code)
	# Compare the provided code with the stored code
	if provided_code == stored_code:
		# Remove the code from the session after it's been used
		del request.session['2FA_code']
		return True
	return False

def sign_in(request):
	if request.method == 'GET':
		try: 
			if request.user.is_authenticated:
				return redirect('index')
		except:
			pass

		form = LoginForm()
		return render(request,'access/login.html', {'form': form})
	
	elif request.method == 'POST':
		form = LoginForm(request.POST)
		
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(request, username=username, password=password)
			print(user)
			if user is not None:

				login(request, user)
				return redirect('index')

				# Assuming you've set up a send_2FA_email function
				send_2FA_email(request, user)
				
				# Store username and password temporarily in session for 2FA verification
				request.session['temp_username'] = username
				request.session['temp_password'] = password
				return redirect('second_factor')
			else:
				messages.error(request, f'Email o contraseña incorrecta.')
		return render(request, 'access/login.html', {'form': form})

def sign_out(request):
	logout(request)
	# messages.success(request,f'You have been logged out.')
	return redirect('login')

def reset_password(request):
    return auth_views.PasswordResetView.as_view()(request)

def second_factor(request):
	if request.method == 'POST':
		form = SecondFactorForm(request.POST)

		if form.is_valid():
			second_factor = form.cleaned_data['second_factor']

			# Verify the 2FA code. Placeholder function here
			is_valid_2fa = verify_2FA_code(request, request.user, second_factor)
			print(is_valid_2fa)
			if is_valid_2fa:
				# Get stored username and password from session
				username = request.session.pop('temp_username', None)
				password = request.session.pop('temp_password', None)
				
				user = authenticate(request, username=username, password=password)
				if user:
					login(request, user)
					return redirect('index')

	form = SecondFactorForm()
	return render(request,'access/second_factor.html',{'form': form}) 

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required



@login_required
def index(request):

	context = {}
	return render(request, 'dashboard/index.html', context)

@login_required
def dashboard_analytics(request):

	context = {}
	return render(request, 'dashboard/dashboard.analytics.html', context)

access/templates/access/base_login.html
{% load static %}
<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable">

<head>

    <meta charset="utf-8" />
    <title>Sign In | Velzon - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">

    <!-- Layout config Js -->
    <script src="{% static 'assets/js/layout.js' %}"></script>
    <!-- Bootstrap Css -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- custom Css-->
    <link href="{% static 'assets/css/custom.min.css' %}" rel="stylesheet" type="text/css" />

</head>

<body>

    <!-- auth-page wrapper -->
    <div class="auth-page-wrapper auth-bg-cover py-5 d-flex justify-content-center align-items-center min-vh-100">
        <div class="bg-overlay"></div>
        <!-- auth-page content -->
        <div class="auth-page-content overflow-hidden pt-lg-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card overflow-hidden">
                            <div class="row g-0">
                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4 auth-one-bg h-100">
                                        <div class="bg-overlay"></div>
                                        <div class="position-relative h-100 d-flex flex-column">
                                            <div class="mb-4">
                                                <a href="index.html" class="d-block">
                                                    <img src="assets/images/logo-light.png" alt="" height="18">
                                                </a>
                                            </div>
                                            <div class="mt-auto">
                                                <div class="mb-3">
                                                    <i class="ri-double-quotes-l display-4 text-success"></i>
                                                </div>

                                                <div id="qoutescarouselIndicators" class="carousel slide" data-bs-ride="carousel">
                                                    <div class="carousel-indicators">
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                                                    </div>
                                                    <div class="carousel-inner text-center text-white-50 pb-5">
                                                        <div class="carousel-item active">
                                                            <p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>
                                                        </div>
                                                        <div class="carousel-item">
                                                            <p class="fs-15 fst-italic">" The theme is really great with an amazing customer support."</p>
                                                        </div>
                                                        <div class="carousel-item">
                                                            <p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- end carousel -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end col -->

                                {% block login_card %}
                                {% endblock %}
                                
                                <!-- end col -->
                            </div>
                            <!-- end row -->
                        </div>
                        <!-- end card -->
                    </div>
                    <!-- end col -->

                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->

        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <p class="mb-0">&copy;
                                <script>document.write(new Date().getFullYear())</script> Molymet. Versión 1.0
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->
    </div>
    <!-- end auth-page-wrapper -->

    <!-- JAVASCRIPT -->
    <script src="{% static 'assets/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static 'assets/libs/node-waves/waves.min.js' %}"></script>
    <script src="{% static 'assets/libs/feather-icons/feather.min.js' %}"></script>
    <script src="{% static 'assets/js/pages/plugins/lord-icon-2.1.0.js' %}"></script>
    <script src="{% static 'assets/js/plugins.js' %}"></script>

    <!-- password-addon init -->
    <script src="{% static 'assets/js/pages/password-addon.init.js' %}"></script>
</body>

</html>

access/templates/access/login.html
{% extends "./base_login.html" %}
{% load static %}

{% block login_card %}

                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4">
                                        <div>
                                            <h5 class="text-primary">Welcome Back !</h5>
                                            <p class="text-muted">Sign in to continue to Velzon.</p>
                                        </div>

                                        <div class="mt-4">
                                            <form method="POST">
                                            	{% csrf_token %}
                                                <div class="mb-3">
                                                    <label for="username" class="form-label">Email</label>
                                                    <input type="text" class="form-control" id="id_username" name="username" placeholder="Enter username">
                                                </div>

                                                <div class="mb-3">
                                                    <div class="float-end">
                                                        <a href="auth-pass-reset-cover.html" class="text-muted">Forgot password?</a>
                                                    </div>
                                                    <label class="form-label" for="password-input">Password</label>
                                                    <div class="position-relative auth-pass-inputgroup mb-3">
                                                        <input type="password" class="form-control pe-5 password-input" placeholder="Enter password" name="password" id="id_password">
                                                        <button class="btn btn-link position-absolute end-0 top-0 text-decoration-none text-muted password-addon" type="button" id="password-addon"><i class="ri-eye-fill align-middle"></i></button>
                                                    </div>
                                                </div>


                                                <div class="mt-4">
                                                    <button class="btn btn-success w-100" type="submit">Entrar</button>
                                                </div>


                                            </form>
                                        </div>

                                    </div>
                                </div>

                                {% endblock %}

access/templates/access/second_factor.html
{% extends "./base_login.html" %}
{% load static %}

{% block login_card %}

				<!-- Content area -->
				<div class="content d-flex justify-content-center align-items-center">

					<!-- Password recovery form -->
					<form class="login-form" method="POST">
						{% csrf_token %}
						<div class="card mb-0">
							<div class="card-body">
								<div class="text-center mb-3">
									<div class="d-inline-flex bg-primary bg-opacity-10 text-primary lh-1 rounded-pill p-3 mb-3 mt-1">
										<i class="ph-arrows-counter-clockwise ph-2x"></i>
									</div>
									<h5 class="mb-0">Segundo factor de autenticación</h5>
									<span class="d-block text-muted">Por favor ingrese la clave enviada al mail.</span>
								</div>

								<div class="mb-3">
									<label class="form-label">Clave de 7 dígitos</label>
									<div class="form-control-feedback form-control-feedback-start">
										<input type="text" class="form-control" placeholder="1234567" name="second_factor" id="id_second_factor">
										<div class="form-control-feedback-icon">
											<i class="ph-lock-key text-muted"></i>
										</div>
									</div>
								</div>

								<button type="submit" class="btn btn-primary w-100">
									<i class="ph-sign-in me-2"></i>
									Ingresar
								</button>
							</div>
						</div>
					</form>
					<!-- /password recovery form -->

				</div>
				<!-- /content area -->

{% endblock %}

dashboard/templates/dashboard/dashboard.analytics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    this is html test
    
</body>
</html>